---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
non-functional:
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь мобильную версию
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы 
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
implicit:
  - Должна быть возможность оплачивать товары
  - Сайт должен отслеживать статус доставки
  - Сайт должен содержать в самом низу графу в которой рассказывается о магазине
  - На сайте должна быть возможность добавления товаров в избранные
  - Должна быть возможность отслеживать товари не в наличии на предмет их появления в продаже
  - Внизу сайта должна быть форма обратной связи
  
 
